title: Peru SERVIR TensorFlow Training Earth Science Applications in Amazonia
description: TensorFlow Earth Science Applications in Amazonia, held in Peru by ACCA, SERVIR Amazonia and Development Seed
baseurl: "/Peru-tensorflow-training" # the subpath of your site, e.g. /blog
url: "https://hayleypippin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/images/transparent-logos.png"

remote_theme: just-the-docs/just-the-docs
